### ISSUE TITLE
能否把MOD整合到自制的MOD安装工具里?

### ISSUE THREAD

**Issue by hanabi1224** [3DMXM/MiChangSheng__ScriptTrainer#3]
这几天做了一个通用的BepInEx Mod图形化安装工具，请问可否把这个mod整合进去？
测试了一下可用
![michangsheng](https://user-images.githubusercontent.com/6546635/127012782-9294b134-e074-471c-88dd-2f2fc6f007c0.jpg)
![michangsheng-config-manager](https://user-images.githubusercontent.com/6546635/127012810-ca6a8cb5-4880-4293-b1bc-505bf7b7d026.jpg)
![michangsheng-in-game](https://user-images.githubusercontent.com/6546635/127012815-a4fa7717-f607-44d4-96c0-d14c833f944c.jpg)
(这个窗口颜色为啥这么糊？？？)
在其他地方发过一个[使用教程](https://nga.178.com/read.php?tid=27778626)
如果mod更新时按要求发布到[这里](https://github.com/hanabi1224/BepInEx.ModRepo)，使用工具的人就能自动收到更新不用自己下载了

P.S. 我把这个插件自己本地编译了一个版本放到[这里](https://github.com/hanabi1224/BepInEx.ModRepo/tree/main/prebuilt/1189490)了, 1189490是觅长生的steam游戏id
![image](https://user-images.githubusercontent.com/6546635/127013625-acf67e30-2ba4-495f-9160-a498f79afc67.png)

**Comment by 3DMXM** [comment]
整合是没有问题的；
至于窗口为什么这么糊，不知道，正常应该是这样的
![](https://mod.3dmgame.com/static/upload/mod/202107/MOD60dee3688bbec.png)

看起来好像是GUIStyle中的background丢失了

**Comment by 3DMXM** [comment]
话说，你提交的  ci 是干嘛用的

**Comment by hanabi1224** [comment]
CI是github action的线上编译啊

**Comment by hanabi1224** [comment]
另外我发现你的ItemData每一帧都加一次物品列表，很快就把游戏卡死了。。。我也给修复了一下
